language: python

dist: xenial
install: pip install --upgrade codecov pip tox virtualenv

jobs:
    include:
        - python: 3.5
          env:
            - TOXENV=py35
        - python: 3.6
          env:
            - TOXENV=py36
        - python: 3.7
          env:
            - TOXENV=py37
        - python: 3.8
          env:
            - TOXENV=py38
        - python: 3.8
          services:
            - postgresql
          before_script:
            - psql -c 'create database travis_ci_test;' -U postgres
          env:
            - FALCON_SQLA_POSTGRESQL_URI=postgresql://postgres:@localhost/travis_ci_test
            - TOXENV=postgresql
          after_success:
            - codecov
        - python: pypy3.6-7.1.1
          services:
            - postgresql
          before_script:
            - psql -c 'create database travis_ci_test;' -U postgres
          env:
            - FALCON_SQLA_POSTGRESQL_URI=postgresql://postgres:@localhost/travis_ci_test
            - TOXENV=pypy3_postgresql
        - python: 3.8
          env:
            - TOXENV=flake8

script:
  - tox
